### ISSUE TITLE
PayPal Link Problem

### ISSUE THREAD

**Issue by ChiefNadeem** [braintree/braintree_aspnet_example#12]
Your Paypal link not working
![screenshot 232](https://cloud.githubusercontent.com/assets/23256459/26399157/51a2ab7e-4095-11e7-9e67-8fb6e7876712.png)

**Comment by bluk** [comment]
Please reach out to [Braintree Support](https://developers.braintreepayments.com/forms/contact) who can help you with your issue. Thanks.
