### ISSUE TITLE
DI object and lifecycle?

### ISSUE THREAD

**Issue by vaindil** [braintree/braintree_aspnet_example#16]
### General information

* **Environment:** N/A
* **Language, language version, and OS:** ASP.NET Core 2.0

### Issue description

Hello! I'm not sure if this is most appropriate to be asked here, on the main Braintree dotnet repo, or sent as an email to support, so I'm trying here. Let me know if it should be asked elsewhere, that way I'll know for the future.

What is the proper way to use ASP.NET Core DI with the library? We're using the built-in DI, but I imagine the answer will be the same for all DI containers. I'm currently using the code below, but I'm not sure if it's right. Can the gateway be a singleton? Should I be injecting something else altogether? Should I create a class like `IBraintreeConfiguration` in this repo and inject that? I can write the code, I just don't know what specifically to inject or what its lifecycle should be. Any advice would be appreciated. Thank you!

Current code in `Startup.cs` / `ConfigureServices()`:

```
// Config values are pulled from appsettings.json
var braintreeGateway = new BraintreeGateway
{
    Environment = Braintree.Environment.SANDBOX,
    MerchantId = Configuration["Braintree:MerchantId"],
    PublicKey = Configuration["Braintree:PublicKey"],
    PrivateKey = Configuration["Braintree:PrivateKey"]
};

// Inject gateway as singleton
services.AddSingleton(braintreeGateway);
```

**Comment by crookedneighbor** [comment]
Sorry for the dealy. There should be no issue with instantiating the gateway as a singleton.

In answer to your first question, it's probably best to send questions like this to our [support team](https://articles.braintreepayments.com/forms/contact).
