### ISSUE TITLE
A project with an Output Type of Class Library cannot be started directly.

### ISSUE THREAD

**Issue by BretMishler** [braintree/braintree_aspnet_example#17]
### General information

* Environment: Sandbox
* Language, language version, and OS: Windows 10, VS 2017, both latest
### Issue description

Upon following the three simple instructions on the README and clicking 'Play' as instructed:

<img width="438" alt="screen shot 2017-12-14 at 7 04 23 pm" src="https://user-images.githubusercontent.com/8965315/34025222-8d2f4f76-e103-11e7-8d5c-d025b7280e08.png">

**Comment by BretMishler** [comment]
Well, I feel foolish. Simple steps are below:

1. Right click the Project name in Solution Explorer of Visual Studio
2. Select Set as StartUp Project from the menu

**Comment by crookedneighbor** [comment]
Glad you were able to figure it out.
