### ISSUE TITLE
Show.html crashes due to Braintree.Transaction' does not contain a definition for 'Customer''

### ISSUE THREAD

**Issue by Todilo** [braintree/braintree_aspnet_example#23]
### General information

* Environment: Sandbox

### Issue description

After downloading code, restoring nuget, setting sandbox keys and then running.
Using card
2223000048400011
02/20

After returning Show.html returns error on lin 101 with

> Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: ''Braintree.Transaction' does not contain a definition for 'Customer''
Customer property does not even exist on object Transaction but rather CustomerDetails. Which unfortunately has only null values.

Nothing in the guide tells you to setup some sort of customerdata.

**Comment by Epreuve** [comment]
Hey @Todilo 
Thanks for catching this one.  We updated `Transaction.Customer` to `Transaction.CustomerDetails` to bring .Net in line with our other SDKs in [4.0.0](https://github.com/braintree/braintree_dotnet/blob/master/CHANGELOG.md#400), and it seems we missed updating this example to reflect those changes.  

We'll take a look as soon as we can, or if you'd like, feel free to submit a PR.

**Comment by Epreuve** [comment]
I just pushed a fix for this, as well as updated the SDK version.  I didn't experience any issues in my testing, so you should be good to go now.  Let us know if you hit any more snags!
