### ISSUE TITLE
Developer Error: Something went wrong. Check the console for details. PayPal payment type is disabled.Getting Error: 91508 - Cannot determine payment method. 

### ISSUE THREAD

**Issue by manishkumar1689** [braintree/braintree_aspnet_example#25]
### General information

* Environment: 
* Language, language version, and OS:

**Comment by Epreuve** [comment]
This typically happens when your sandbox isn't setup to support PayPal as a payment method.  You can reach out to support@braintreepayments.com for assistance with resolving this issue.
