### ISSUE TITLE
Why there isn't any enableBillingAddress in paypal hosted fields?

### ISSUE THREAD

**Issue by khanrafay** [braintree/braintree_aspnet_example#29]
### General information

* Environment: Sandbox
* Language, language version, and OS:  Windows, C# , .NET
### Issue description

I am getting the shipping address in return from paypal but there isn't any billingaddress option there.

**Comment by crookedneighbor** [comment]
Can you explain a bit more what you're asking?

**Comment by khanrafay** [comment]
payment: function () {
                        return paypalCheckoutInstance.createPayment({

                            flow: "checkout",
                            displayName: "ABC",
                            //container: "paypal-container",
                            singleUse: true, // Required
                            amount: braintreeManager.amount, // Required
                            currency: 'US', // Required
                            locale: 'en_gb',
                            enableShippingAddress: true,
                        });


Now there is this option of enableshippingaddress, which returns shipping address, but there ain't any of  enablebillingaddress.
I read that in order to have that we need to enable it manually from paypal or contact the technical support team.
so just wanted to know if you know how to enable that feature.

Thanks.

**Comment by crookedneighbor** [comment]
This doesn't look related to this example repo. Your question can be better answered by our support team. https://help.braintreepayments.com/
