### ISSUE TITLE
'Some of your info isn't correct. Please try again" Pay by paypal login Error

### ISSUE THREAD

**Issue by ajitgoel** [braintree/braintree_aspnet_example#30]
i am running the sample application and using paypal to make a test payment. i get a login screen but I am unable to login into paypal to make a test payment. I get a 'Some of your info isn't correct. Please try again." error even though i know that my login details are correct. 

I also get the following 2 errors on my chrome console. What am I missing? 

**Cross-Origin Read Blocking (CORB) blocked cross-origin response https://www.paypal.com/xoplatform/logger/api/logger with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.**
(anonymous) @ util.js:71
e @ promise.js:41
(anonymous) @ util.js:35
v @ logger.js:10
(anonymous) @ proxy.js:37
_ @ logger.js:111
(anonymous) @ util.js:98
l @ promise.js:161
o.dispatch @ promise.js:152
o.then @ promise.js:241
(anonymous) @ util.js:97
setTimeout (async)
A @ util.js:87
(anonymous) @ setup.js:275
l @ promise.js:161
o.dispatch @ promise.js:152
o.resolve @ promise.js:96
l @ promise.js:212
o.dispatch @ promise.js:152
o.resolve @ promise.js:96
(anonymous) @ promise.js:43
Promise.then (async)
(anonymous) @ promise.js:309
e @ promise.js:41
e.resolve @ promise.js:309
e.try @ promise.js:408
(anonymous) @ setup.js:242
a @ bootstrap:19
(anonymous) @ load.js:32
a @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ bootstrap:83

**util.js:71 POST https://www.sandbox.paypal.com/xoplatform/logger/api/logger net::ERR_CONNECTION_RESET**
(anonymous) @ util.js:71
e @ promise.js:41
(anonymous) @ util.js:35
v @ logger.js:10
_ @ logger.js:111
(anonymous) @ util.js:98
l @ promise.js:161
o.dispatch @ promise.js:152
o.then @ promise.js:241
(anonymous) @ util.js:97
setTimeout (async)
A @ util.js:87
(anonymous) @ component.js:465
n @ props.js:88
(anonymous) @ fn.js:35
(anonymous) @ serialize.js:34
e.try @ promise.js:400
(anonymous) @ serialize.js:33
(anonymous) @ types.js:68
e.try @ promise.js:400
f.<computed> @ types.js:56
_ @ index.js:114
L @ index.js:140

**Comment by ajitgoel** [comment]
![image](https://user-images.githubusercontent.com/6394444/58217507-b98f7200-7cc8-11e9-8580-60cf3cc75e31.png)

![image](https://user-images.githubusercontent.com/6394444/58217520-ce6c0580-7cc8-11e9-9440-f3a4ce243724.png)

**Comment by Epreuve** [comment]
It doesn't look like you're using a PayPal sandbox account, but rather your actual PayPal account.  You'll need to follow the directions [here](https://developers.braintreepayments.com/guides/paypal/testing-go-live/ruby#linked-paypal-testing) to setup a PayPal sandbox test account to use during testing.  

Please reach out to [Braintree Support](https://help.braintreepayments.com/) if you have any questions about getting this setup.

**Comment by Rifqa123** [comment]
Hi, I have the Paypal smart button launched live on our site but we're getting the same issue. We're not testing so we weren't looking for sandbox. Any reason why this should be happening?

**Comment by crookedneighbor** [comment]
@Rifqa123 reach out to our support team for help: https://help.braintreepayments.com/

**Comment by saggie69** [comment]
> Hi, I have the Paypal smart button launched live on our site but we're getting the same issue. We're not testing so we weren't looking for sandbox. Any reason why this should be happening?

DID YOU FIND ANY SOLUTION?!!? PLEASE HELP!! :(

**Comment by crookedneighbor** [comment]
@saggie69 Same answer. Reach out to our support team. https://help.braintreepayments.com/
