### ISSUE TITLE
Does not contain code for all braintree payment methods

### ISSUE THREAD

**Issue by MSIH** [braintree/braintree_aspnet_example#33]
### General information

Does not contain code for all braintree payment methods: applepay, venmo, and ach,

**Comment by crookedneighbor** [comment]
This is not intended as a full example. Please reach out to our support team if you need assistance. https://developer.paypal.com/braintree/help

**Comment by MSIH** [comment]
Wow. you will not cut and paste the example code you have on your website to your git repo and provide the community with a working example. Very disappointed.
