### ISSUE TITLE
Onboarding Sub-merchants is not working 

### ISSUE THREAD

**Issue by Umar-Abbas** [braintree/braintree_aspnet_example#7]
Hi ,

I am working with dot net SDK of braintree but it seems it is not recognizing the object like **MerchantAccountRequest and TransactionRequest** for marketplace

///////////
var request = new TransactionRequest
{
    MerchantAccountId = "provider_sub_merchant_account",
    Amount = 10.00M,
    PaymentMethodNonce = nonceFromTheClient,
    ServiceFeeAmount = 10.00m
};

Result<Transaction> result = gateway.Transaction.Sale(request);
/////////////////////

MerchantAccountRequest request = new MerchantAccountRequest
{
  Individual = new IndividualRequest
  {
    FirstName = "Jane",
    LastName = "Doe",
    Email = "jane@14ladders.com",
    Phone = "5553334444",
    DateOfBirth = "1981-11-19",
    Ssn = "456-45-4567",
    Address = new AddressRequest
    {
      StreetAddress = "111 Main St",
      Locality = "Chicago",
      Region = "IL",
      PostalCode = "60622"
    }
  },
  Business = new BusinessRequest
  {
    LegalName = "Jane's Ladders",
    DbaName = "Jane's Ladders",
    TaxId = "98-7654321",
    Address = new AddressRequest
    {
      StreetAddress = "111 Main St",
      Locality = "Chicago",
      Region = "IL",
      PostalCode = "60622"
    }
  },
  Funding = new FundingRequest
  {
    Descriptor = "Blue Ladders",
    Destination = FundingDestination.BANK,
    Email = "funding@blueladders.com",
    MobilePhone = "5555555555",
    AccountNumber = "1123581321",
    RoutingNumber = "071101307"
  },
  TosAccepted = true,
  MasterMerchantAccountId = "14ladders_marketplace",
  Id = "blue_ladders_store"
};

Result<MerchantAccount> result = gateway.MerchantAccount.Create(request);

**Comment by crookedneighbor** [comment]
This is not relevant to the this repository. 

I recommend emailing our support team at support@braintreepayments.com for help with your integration.
