### ISSUE TITLE
Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by marcolsh** [braintree/braintree_aspnet_example#8]
As of 2016.12.14, we encountered an issue generate client token on a machine without SSL, such as SANDBOX or testing environment.

Tried your example, its great and thanks for sharing and teaching.
Submitting this issue would like to question about should example add following 2 lines before generate the token? so that the example would works great as it download.

ServicePointManager.Expect100Continue = true;
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

Thank you.

**Comment by danakatz** [comment]
Hi @marcolsh,

Apologies for the interruption here! The Braintree sandbox environment now requires TLSv1.2 connections, which are supported starting with version 3.1.0 of the Braintree .NET SDK. The example is currently using 2.59.0.

I just opened a PR (#9) to get everything updated -- feel free to make those changes locally in the meantime!

**Comment by marcolsh** [comment]
Hi danakatz,

Great thanks for your reply and corrected my misunderstanding.
:+1:

**Comment by github-john-doe** [comment]
Why not merge the pull request?
